### ISSUE TITLE
Markers sometimes fail to render

### ISSUE THREAD

**Issue by geohouse** [geohouse/MN_cropRotations#4]

**Comment by geohouse** [comment]
Sometimes the markers function errors out intermittently and sometimes succeeds with *the same data call* - I think it may be a partially corrupted data error. 
This doesn't affect the loading message disappearing, since that is done after the lines are rendered (and there's a workable graph on the page, just not with the markers showing) 
```
Error: gd.data must be an array.
    at plotly-latest.min.js:61:551045
    at Object.t [as addTraces] (plotly-latest.min.js:61:551508)
    at processData_markers (cropRotateInteractiveGraphingModule.js:330:12)
    at cropRotateInteractiveGraphingModule.js:423:9


(anonymous) | @ | cropRotateInteractiv…aphingModule.js:425
-- | -- | --
  | Promise.catch (async) |   |  
  | renderPlot | @ | cropRotateInteractiv…aphingModule.js:425
  | makeInteractivePlot | @ | cropRotateInteractiv…aphingModule.js:428
  | (anonymous) | @ | cropRotateMapboxPlot.js:475
  | fire | @ | evented.js:129
  | click | @ | map_event.js:54
  | handleEvent | @ | handler_manager.js:381
```

**Comment by geohouse** [comment]
Seems to generally be the case the first time the graph is clicked in the map (and therefore the first time the data is loaded and tried graphing). If click on the same graph in the map a second time, the markers usually load and appear correctly
